name: Deploy RIS Channel Estimation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with Streamlit
      run: |
        streamlit run RIS_Demo_Streamlit.py --server.headless true --server.port 8501 &
        sleep 10
        curl -f http://localhost:8501 || exit 1

  deploy-streamlit:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Deploy to Streamlit Cloud by connecting your repository at share.streamlit.io"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: main"
        echo "Main file: RIS_Demo_Streamlit.py" 